# Generated by Django 5.2.15 on 2026-10-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build', '0062_quickbuild_quickbuildline'),
        ('stock', '0125_quarantine_disassembly_recoveries'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='consumed_by_quick_build',
            field=models.ForeignKey(blank=True, help_text='Quick build which consumed this stock item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumed_stock', to='build.quickbuild', verbose_name='Consumed By Quick Build'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='quick_build',
            field=models.ForeignKey(blank=True, help_text='Quick build which produced this stock item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='build.quickbuild', verbose_name='Source Quick Build'),
        ),
    ]
