# Generated by Django 5.2.15 on 2026-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0150_part_maximum_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='quick_build',
            field=models.BooleanField(default=False, help_text='Can this assembly be produced by a quick build, without a build order?', verbose_name='Quick Build'),
        ),
    ]
