# Generated by Django 5.2.15 on 2026-10-09 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_p3_task_description'),
        ('stock', '0126_stockitem_consumed_by_quick_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripkitline',
            name='stock_item',
            field=models.ForeignKey(blank=True, help_text='The device to take (a device to deploy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_trip_kit_lines', to='stock.stockitem', verbose_name='Stock Item'),
        ),
        migrations.AddField(
            model_name='tripkitline',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task which needs this line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_lines', to='fleet.maintenancetask', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='tripkitline',
            name='source',
            field=models.CharField(choices=[('ALWAYS', 'Always'), ('LIKELY', 'Likely'), ('ALERT', 'Alert'), ('MANUAL', 'Manual'), ('DEVICE', 'Device to deploy')], default='MANUAL', max_length=20, verbose_name='Source'),
        ),
    ]
